[package]
name = "hedge-bot"
version = "0.1.0"
authors = ["fromif <klee78736@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
