[package]
name = "hb"
version = "0.1.0"
authors = ["Kevin Lee <klee78736@gmail.com>"]
edition = "2018"

[dependencies]
web3 = "0.13.0"
tokio = { version = "0.2.21", features = ["full"] }
env_logger = "0.7.1"
log = "0.4.11"